#!/usr/bin/env bash
# Bash script that will display information about subdomains.
# shellcheck disable=SC2086

if [ $# -lt 2 ]; then
	sub_domains=('www' 'lb-01' 'web-01' 'web-02')
	for sub_domain in "${sub_domains[@]}"
	do
		type="$(dig "$sub_domain.$1" | grep -A1 'ANSWER SECTION' | awk '{print $4}' | tr -d '\n')"
		ip="$(dig "$sub_domain.$1" | grep -A1 'ANSWER SECTION' | awk '{print $5}' | tr -d '\n')"
		echo "The subdomain $sub_domain is a $type record and points to $ip"
	done
else
	type="$(dig "$2.$1" | grep -A1 'ANSWER SECTION' | awk '{print $4}' | tr -d '\n')"
	ip="$(dig "$2.$1" | grep -A1 'ANSWER SECTION' | awk '{print $5}' | tr -d '\n')"
	echo "The subdomain $2 is a $type record and points to $ip"
fi
