#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cat >> /etc/haproxy/haproxy.cfg << EOF

frontend front_server
	bind *:80
	mode http
	default_backend backend_server
backend backend_server
	balance roundrobin
	server 1647-web-01 104.196.165.127:80 check
	server 1647-web-02 34.230.11.25:80 check

EOF

echo "ENABLED=1" >> /etc/default/haproxy
sudo service haproxy restart
