#!/usr/bin/env bash
# Bash script that displayes Holberton School 10 times using while
i=0
while [ $i -lt 10 ] 
do
	if [ $i -eq 8 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	((i++))
done
