#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

file="/etc/passwd"

if [ -e $file ]; then
	while IFS= read -r line
	do
		USERNAME=$line | cut -f 1 -d ':'
		GROUP_ID=$line | cut -f 4 -d ':'
		HOME_DIRECTORY=$line | cut -f 6 -d ':'
		COMMAND_SHELL=$line | cut -f 7 -d ':'
		PASSWORD=$line | cut -f 2 -d':'
		USER_ID_INFO=$line | cut -f 5 -d ':'
		USER_ID=$line | cut -f 3 -d ':'
		echo "The user $USERNAME is part of the ${GROUP_ID} gang, lives in ${HOME_DIRECTORY} and rides ${COMMAND_SHELL}, ${USER_ID} place is protected by the passcode ${PASSWORD}, more info about the user here: ${USER_ID_INFO}"
	done < "$file"
fi
