#!/usr/bin/env bash
# Bash script that displayes info about the holbertonschool file
if [ -e "./holbertonschool" ]; then
	echo "holbertonschool file exists"
	if [ ! -s "./holbertonschool" ]; then
		echo "holbertonschool file is empty"
	elif [ -s "./holbertonschool" ];  then
		echo "holbertonschool file is not empty"
	fi
	if [ -f "./holbertonschool" ]; then
		echo "holbertonschool is a regular file"
	fi
elif [ ! -e "./holbertonschool" ]; then
	echo "holbertonschool file does not exist"
fi
