#!/usr/bin/env bash
#  script that configures the container to fit the requirements
sudo chown -R nginx:nginx /etc/nginx/
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chown 0700 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx restart
